//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class AppDTEntities : DbContext
    {
        public AppDTEntities()
            : base("name=AppDTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CUSTOMER> CUSTOMER { get; set; }
        public DbSet<GETSURVEY> GETSURVEY { get; set; }
        public DbSet<INSTALLER> INSTALLER { get; set; }
        public DbSet<NOTVISIT> NOTVISIT { get; set; }
        public DbSet<PAQUETE> PAQUETE { get; set; }
        public DbSet<PAQUETE_DETALLE> PAQUETE_DETALLE { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<RETURN> RETURN { get; set; }
        public DbSet<SURVEY> SURVEY { get; set; }
        public DbSet<SURVEY_CUESTION> SURVEY_CUESTION { get; set; }
        public DbSet<SURVEY_CUESTION_ANSWARE> SURVEY_CUESTION_ANSWARE { get; set; }
        public DbSet<SURVEY_CUESTION_OP> SURVEY_CUESTION_OP { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VISITA_ASSIGN> VISITA_ASSIGN { get; set; }
        public DbSet<VISITA_IMAGE_NEW> VISITA_IMAGE_NEW { get; set; }
        public DbSet<VISITA_REGISTRO> VISITA_REGISTRO { get; set; }
        public DbSet<vis_Assigned_Visit> vis_Assigned_Visit { get; set; }
        public DbSet<vis_survey> vis_survey { get; set; }
        public DbSet<vis_Survey_Data> vis_Survey_Data { get; set; }
        public DbSet<vis_VISITA_CUSTOMER> vis_VISITA_CUSTOMER { get; set; }
        public DbSet<vis_VISITA_NOTVISIT> vis_VISITA_NOTVISIT { get; set; }
        public DbSet<vis_VISITA_REGISTRO> vis_VISITA_REGISTRO { get; set; }
        public DbSet<vis_PAQUETE_DETALLE> vis_PAQUETE_DETALLE { get; set; }
    
        public virtual ObjectResult<sp_Busqueda_Visitas_Assign_Result> sp_Busqueda_Visitas_Assign(string dateIni, string dateEnd)
        {
            var dateIniParameter = dateIni != null ?
                new ObjectParameter("dateIni", dateIni) :
                new ObjectParameter("dateIni", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Busqueda_Visitas_Assign_Result>("sp_Busqueda_Visitas_Assign", dateIniParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<sp_Login_Device_Result> sp_Login_Device(string inst_name, string phone)
        {
            var inst_nameParameter = inst_name != null ?
                new ObjectParameter("inst_name", inst_name) :
                new ObjectParameter("inst_name", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Login_Device_Result>("sp_Login_Device", inst_nameParameter, phoneParameter);
        }
    
        public virtual ObjectResult<sp_Visitas_Assign_Result> sp_Visitas_Assign(Nullable<int> inst_id, string dateIni, string dateEnd)
        {
            var inst_idParameter = inst_id.HasValue ?
                new ObjectParameter("inst_id", inst_id) :
                new ObjectParameter("inst_id", typeof(int));
    
            var dateIniParameter = dateIni != null ?
                new ObjectParameter("dateIni", dateIni) :
                new ObjectParameter("dateIni", typeof(string));
    
            var dateEndParameter = dateEnd != null ?
                new ObjectParameter("dateEnd", dateEnd) :
                new ObjectParameter("dateEnd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Visitas_Assign_Result>("sp_Visitas_Assign", inst_idParameter, dateIniParameter, dateEndParameter);
        }
    
        public virtual ObjectResult<sp_Visitas_Assign_Grid_Result> sp_Visitas_Assign_Grid(string dateIni)
        {
            var dateIniParameter = dateIni != null ?
                new ObjectParameter("dateIni", dateIni) :
                new ObjectParameter("dateIni", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Visitas_Assign_Grid_Result>("sp_Visitas_Assign_Grid", dateIniParameter);
        }
    }
}
