//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTVISIT
    {
        public int novi_id { get; set; }
        public Nullable<int> vist_id { get; set; }
        public string inst_id { get; set; }
        public Nullable<System.DateTime> novi_date { get; set; }
        public string novi_reazon { get; set; }
    }
}
