//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE_DETALLE
    {
        public int paqu_detail_id { get; set; }
        public int paqu_id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public Nullable<int> prod_cant { get; set; }
        public string prod_observ { get; set; }
    }
}
