//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAQUETE
    {
        public int paqu_id { get; set; }
        public string paqu_codigo { get; set; }
        public int paqu_cantidad { get; set; }
        public string paqu_observ { get; set; }
        public Nullable<System.DateTime> paqu_fecha { get; set; }
        public Nullable<int> paqu_status { get; set; }
    }
}
