//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public int prod_id { get; set; }
        public string prod_codigo { get; set; }
        public string prod_name { get; set; }
        public string prod_unidad { get; set; }
    }
}
