//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETURN
    {
        public int retu_id { get; set; }
        public Nullable<int> paqu_id { get; set; }
        public int prod_id { get; set; }
        public Nullable<int> prod_cant { get; set; }
        public string prod_unit { get; set; }
        public string retu_reason { get; set; }
    }
}
