//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_CUESTION_OP
    {
        public int op_id { get; set; }
        public int surv_id { get; set; }
        public Nullable<int> surv_c1 { get; set; }
        public Nullable<int> surv_r1 { get; set; }
        public Nullable<int> surv_c2 { get; set; }
        public Nullable<int> surv_r2 { get; set; }
        public string surv_txt { get; set; }
        public Nullable<int> visi_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    }
}
