//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SURVEY_CUESTION_ANSWARE
    {
        public int surv_answare_id { get; set; }
        public int surv_cuestion_id { get; set; }
        public int surv_id { get; set; }
        public string surv_answare { get; set; }
        public string surv_deleted { get; set; }
    }
}
