//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int Usua_Id { get; set; }
        public string Usua_nombre { get; set; }
        public string Usua_Telefono { get; set; }
        public string Usua_Email { get; set; }
        public string Usua_Login { get; set; }
        public string Usua_Password { get; set; }
        public string Usua_Activo { get; set; }
        public Nullable<System.DateTime> Usua_FechaCreacion { get; set; }
    }
}
