//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_VISITA_NOTVISIT
    {
        public int reg_id { get; set; }
        public int visi_id { get; set; }
        public Nullable<int> inst_id { get; set; }
        public string inst_name { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string cust_name { get; set; }
        public string reg_ini { get; set; }
        public string reg_end { get; set; }
        public Nullable<int> reg_status { get; set; }
        public string novi_reazon { get; set; }
        public string reg_date { get; set; }
    }
}
