//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_Survey_Data
    {
        public int surv_id { get; set; }
        public Nullable<int> surv_r1 { get; set; }
        public Nullable<int> surv_r2 { get; set; }
        public string surv_txt { get; set; }
        public Nullable<int> visi_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public string cust_name { get; set; }
        public Nullable<int> inst_id { get; set; }
        public string inst_name { get; set; }
        public string reg_date { get; set; }
    }
}
