//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vis_survey
    {
        public int surv_id { get; set; }
        public string surv_name { get; set; }
        public int surv_cuestion_id { get; set; }
        public string surv_name_custion { get; set; }
        public string surv_type_cuestion { get; set; }
    }
}
