//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA_IMAGE_NEW
    {
        public int imag_id { get; set; }
        public int visi_id { get; set; }
        public string imag_name { get; set; }
        public byte[] imag_image { get; set; }
    }
}
